
/**************************************************************
 *	
 *	choosingSound, 8 bit, 11025Hz,
 *	1 channel, 1314 bytes/channel
 *	Total Size: 1 * 1314 + 4 (header) = 1358 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Spring2019\CS2261\Final Project\Sound\Sound\EditedSongs\Sound Effects\choosingSound.wav
 *	Time-stamp: Sun Apr 21 17:37:23 2019
 *	
 **************************************************************/

#ifndef __CHOOSINGSOUNDH__
#define __CHOOSINGSOUNDH__

#define CHOOSINGSOUNDFREQ 11025
#define CHOOSINGSOUNDLEN 1314

extern const unsigned char choosingSound[1314];

#endif /* __CHOOSINGSOUNDH__ */
