
/**************************************************************
 *	
 *	EndGameSong, 8 bit, 11025Hz,
 *	1 channel, 1480320 bytes/channel
 *	Total Size: 1 * 1480320 + 4 (header) = 1480364 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Spring2019\CS2261\Final Project\Sound\Sound\EditedSongs\BGM\EndGameSong.wav
 *	Time-stamp: Sun Apr 21 13:43:14 2019
 *	
 **************************************************************/

#ifndef __ENDGAMESONGH__
#define __ENDGAMESONGH__

#define ENDGAMESONGFREQ 11025
#define ENDGAMESONGLEN 1480320

extern const unsigned char EndGameSong[1480320];

#endif /* __ENDGAMESONGH__ */
