
/**************************************************************
 *	
 *	gameEntranceSound, 8 bit, 11025Hz,
 *	1 channel, 23040 bytes/channel
 *	Total Size: 1 * 23040 + 4 (header) = 23084 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Spring2019\CS2261\Final Project\Sound\Sound\EditedSongs\Sound Effects\gameEntranceSound.wav
 *	Time-stamp: Fri Apr 19 23:56:46 2019
 *	
 **************************************************************/

#ifndef __GAMEENTRANCESOUNDH__
#define __GAMEENTRANCESOUNDH__

#define GAMEENTRANCESOUNDFREQ 11025
#define GAMEENTRANCESOUNDLEN 23040

extern const unsigned char gameEntranceSound[23040];

#endif /* __GAMEENTRANCESOUNDH__ */
