
/**************************************************************
 *	
 *	getHitSound, 8 bit, 11025Hz,
 *	1 channel, 9181 bytes/channel
 *	Total Size: 1 * 9181 + 4 (header) = 9225 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Spring2019\CS2261\Final Project\Sound\Sound\EditedSongs\Sound Effects\getHitSound.wav
 *	Time-stamp: Sun Apr 21 17:18:24 2019
 *	
 **************************************************************/

#ifndef __GETHITSOUNDH__
#define __GETHITSOUNDH__

#define GETHITSOUNDFREQ 11025
#define GETHITSOUNDLEN 9181

extern const unsigned char getHitSound[9181];

#endif /* __GETHITSOUNDH__ */
