
/**************************************************************
 *	
 *	MainGameSong, 8 bit, 11025Hz,
 *	1 channel, 3786336 bytes/channel
 *	Total Size: 1 * 3786336 + 4 (header) = 3786380 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Spring2019\CS2261\Final Project\Sound\Sound\EditedSongs\BGM\MainGameSong.wav
 *	Time-stamp: Sun Apr 21 13:43:18 2019
 *	
 **************************************************************/

#ifndef __MAINGAMESONGH__
#define __MAINGAMESONGH__

#define MAINGAMESONGFREQ 11025
#define MAINGAMESONGLEN 3786336

extern const unsigned char MainGameSong[3786336];

#endif /* __MAINGAMESONGH__ */
