
/**************************************************************
 *	
 *	PAROMASound, 8 bit, 11025Hz,
 *	1 channel, 12688 bytes/channel
 *	Total Size: 1 * 12688 + 4 (header) = 12732 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Spring2019\CS2261\Final Project\Sound\Sound\EditedSongs\Sound Effects\PAROMASound.wav
 *	Time-stamp: Mon Apr 22 20:41:03 2019
 *	
 **************************************************************/

#ifndef __PAROMASOUNDH__
#define __PAROMASOUNDH__

#define PAROMASOUNDFREQ 11025
#define PAROMASOUNDLEN 12688

extern const unsigned char PAROMASound[12688];

#endif /* __PAROMASOUNDH__ */
