
/**************************************************************
 *	
 *	PAROMALoseSound, 8 bit, 11025Hz,
 *	1 channel, 55831 bytes/channel
 *	Total Size: 1 * 55831 + 4 (header) = 55875 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Spring2019\CS2261\Final Project\Sound\Sound\EditedSongs\Sound Effects\PAROMALoseSound.wav
 *	Time-stamp: Sat Apr 20 13:02:52 2019
 *	
 **************************************************************/

#ifndef __PAROMALOSESOUNDH__
#define __PAROMALOSESOUNDH__

#define PAROMALOSESOUNDFREQ 11025
#define PAROMALOSESOUNDLEN 55831

extern const unsigned char PAROMALoseSound[55831];

#endif /* __PAROMALOSESOUNDH__ */
