
/**************************************************************
 *	
 *	PAROMAWinSound, 8 bit, 11025Hz,
 *	1 channel, 59616 bytes/channel
 *	Total Size: 1 * 59616 + 4 (header) = 59660 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Spring2019\CS2261\Final Project\Sound\Sound\EditedSongs\Sound Effects\PAROMAWinSound.wav
 *	Time-stamp: Sat Apr 20 13:20:12 2019
 *	
 **************************************************************/

#ifndef __PAROMAWINSOUNDH__
#define __PAROMAWINSOUNDH__

#define PAROMAWINSOUNDFREQ 11025
#define PAROMAWINSOUNDLEN 59616

extern const unsigned char PAROMAWinSound[59616];

#endif /* __PAROMAWINSOUNDH__ */
