
/**************************************************************
 *	
 *	ParomaSong, 8 bit, 11025Hz,
 *	1 channel, 866880 bytes/channel
 *	Total Size: 1 * 866880 + 4 (header) = 866924 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Spring2019\CS2261\Final Project\Sound\Sound\EditedSongs\BGM\ParomaSong.wav
 *	Time-stamp: Sun Apr 21 13:43:26 2019
 *	
 **************************************************************/

#ifndef __PAROMASONGH__
#define __PAROMASONGH__

#define PAROMASONGFREQ 11025
#define PAROMASONGLEN 866880

extern const unsigned char ParomaSong[866880];

#endif /* __PAROMASONGH__ */
