
/**************************************************************
 *	
 *	PAROMAFireSound, 8 bit, 11025Hz,
 *	1 channel, 7243 bytes/channel
 *	Total Size: 1 * 7243 + 4 (header) = 7287 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Spring2019\CS2261\Final Project\Sound\Sound\EditedSongs\Sound Effects\PAROMAFireSound.wav
 *	Time-stamp: Tue Apr 23 13:30:56 2019
 *	
 **************************************************************/

#ifndef __PAROMAFIRESOUNDH__
#define __PAROMAFIRESOUNDH__

#define PAROMAFIRESOUNDFREQ 11025
#define PAROMAFIRESOUNDLEN 7243

extern const unsigned char PAROMAFireSound[7243];

#endif /* __PAROMAFIRESOUNDH__ */
