
/**************************************************************
 *	
 *	rollingDiceSound, 8 bit, 11025Hz,
 *	1 channel, 23040 bytes/channel
 *	Total Size: 1 * 23040 + 4 (header) = 23084 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Spring2019\CS2261\Final Project\Sound\Sound\EditedSongs\Sound Effects\rollingDiceSound.wav
 *	Time-stamp: Sat Apr 20 13:26:28 2019
 *	
 **************************************************************/

#ifndef __ROLLINGDICESOUNDH__
#define __ROLLINGDICESOUNDH__

#define ROLLINGDICESOUNDFREQ 11025
#define ROLLINGDICESOUNDLEN 23040

extern const unsigned char rollingDiceSound[23040];

#endif /* __ROLLINGDICESOUNDH__ */
