
/**************************************************************
 *	
 *	RPSDrawSound, 8 bit, 11025Hz,
 *	1 channel, 14865 bytes/channel
 *	Total Size: 1 * 14865 + 4 (header) = 14909 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Spring2019\CS2261\Final Project\Sound\Sound\EditedSongs\Sound Effects\RPSDrawSound.wav
 *	Time-stamp: Sun Apr 21 17:54:19 2019
 *	
 **************************************************************/

#ifndef __RPSDRAWSOUNDH__
#define __RPSDRAWSOUNDH__

#define RPSDRAWSOUNDFREQ 11025
#define RPSDRAWSOUNDLEN 14865

extern const unsigned char RPSDrawSound[14865];

#endif /* __RPSDRAWSOUNDH__ */
