
/**************************************************************
 *	
 *	RPSGameSong, 8 bit, 11025Hz,
 *	1 channel, 1349856 bytes/channel
 *	Total Size: 1 * 1349856 + 4 (header) = 1349900 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Spring2019\CS2261\Final Project\Sound\Sound\EditedSongs\BGM\RPSGameSong.wav
 *	Time-stamp: Sun Apr 21 13:43:29 2019
 *	
 **************************************************************/

#ifndef __RPSGAMESONGH__
#define __RPSGAMESONGH__

#define RPSGAMESONGFREQ 11025
#define RPSGAMESONGLEN 1349856

extern const unsigned char RPSGameSong[1349856];

#endif /* __RPSGAMESONGH__ */
