
/**************************************************************
 *	
 *	RPSLoseSound, 8 bit, 11025Hz,
 *	1 channel, 40896 bytes/channel
 *	Total Size: 1 * 40896 + 4 (header) = 40940 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Spring2019\CS2261\Final Project\Sound\Sound\EditedSongs\Sound Effects\RPSLoseSound.wav
 *	Time-stamp: Wed Apr 17 01:41:54 2019
 *	
 **************************************************************/

#ifndef __RPSLOSESOUNDH__
#define __RPSLOSESOUNDH__

#define RPSLOSESOUNDFREQ 11025
#define RPSLOSESOUNDLEN 40896

extern const unsigned char RPSLoseSound[40896];

#endif /* __RPSLOSESOUNDH__ */
