
/**************************************************************
 *	
 *	RPSWinSound, 8 bit, 11025Hz,
 *	1 channel, 22464 bytes/channel
 *	Total Size: 1 * 22464 + 4 (header) = 22508 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Spring2019\CS2261\Final Project\Sound\Sound\EditedSongs\Sound Effects\RPSWinSound.wav
 *	Time-stamp: Wed Apr 17 01:49:49 2019
 *	
 **************************************************************/

#ifndef __RPSWINSOUNDH__
#define __RPSWINSOUNDH__

#define RPSWINSOUNDFREQ 11025
#define RPSWINSOUNDLEN 22464

extern const unsigned char RPSWinSound[22464];

#endif /* __RPSWINSOUNDH__ */
