
/**************************************************************
 *	
 *	SRCrowdSound, 8 bit, 11025Hz,
 *	1 channel, 459936 bytes/channel
 *	Total Size: 1 * 459936 + 4 (header) = 459980 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Spring2019\CS2261\Final Project\Sound\Sound\EditedSongs\Sound Effects\SRCrowdSound.wav
 *	Time-stamp: Mon Apr 22 13:35:34 2019
 *	
 **************************************************************/

#ifndef __SRCROWDSOUNDH__
#define __SRCROWDSOUNDH__

#define SRCROWDSOUNDFREQ 11025
#define SRCROWDSOUNDLEN 459936

extern const unsigned char SRCrowdSound[459936];

#endif /* __SRCROWDSOUNDH__ */
