
/**************************************************************
 *	
 *	StartGameSong, 8 bit, 11025Hz,
 *	1 channel, 1270368 bytes/channel
 *	Total Size: 1 * 1270368 + 4 (header) = 1270412 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Spring2019\CS2261\Final Project\Sound\Sound\EditedSongs\BGM\StartGameSong.wav
 *	Time-stamp: Sun Apr 21 13:43:36 2019
 *	
 **************************************************************/

#ifndef __STARTGAMESONGH__
#define __STARTGAMESONGH__

#define STARTGAMESONGFREQ 11025
#define STARTGAMESONGLEN 1270368

extern const unsigned char StartGameSong[1270368];

#endif /* __STARTGAMESONGH__ */
