
/**************************************************************
 *	
 *	SwimmingRaceSong, 8 bit, 11025Hz,
 *	1 channel, 2352096 bytes/channel
 *	Total Size: 1 * 2352096 + 4 (header) = 2352140 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Spring2019\CS2261\Final Project\Sound\Sound\EditedSongs\BGM\SwimmingRaceSong.wav
 *	Time-stamp: Sun Apr 21 13:43:39 2019
 *	
 **************************************************************/

#ifndef __SWIMMINGRACESONGH__
#define __SWIMMINGRACESONGH__

#define SWIMMINGRACESONGFREQ 11025
#define SWIMMINGRACESONGLEN 2352096

extern const unsigned char SwimmingRaceSong[2352096];

#endif /* __SWIMMINGRACESONGH__ */
