
/**************************************************************
 *	
 *	THFailSound, 8 bit, 11025Hz,
 *	1 channel, 4320 bytes/channel
 *	Total Size: 1 * 4320 + 4 (header) = 4364 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Spring2019\CS2261\Final Project\Sound\Sound\EditedSongs\Sound Effects\THFailSound.wav
 *	Time-stamp: Wed Apr 17 02:01:16 2019
 *	
 **************************************************************/

#ifndef __THFAILSOUNDH__
#define __THFAILSOUNDH__

#define THFAILSOUNDFREQ 11025
#define THFAILSOUNDLEN 4320

extern const unsigned char THFailSound[4320];

#endif /* __THFAILSOUNDH__ */
