
/**************************************************************
 *	
 *	THGameSong, 8 bit, 11025Hz,
 *	1 channel, 2721312 bytes/channel
 *	Total Size: 1 * 2721312 + 4 (header) = 2721356 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Spring2019\CS2261\Final Project\Sound\Sound\EditedSongs\BGM\THGameSong.wav
 *	Time-stamp: Sun Apr 21 13:43:43 2019
 *	
 **************************************************************/

#ifndef __THGAMESONGH__
#define __THGAMESONGH__

#define THGAMESONGFREQ 11025
#define THGAMESONGLEN 2721312

extern const unsigned char THGameSong[2721312];

#endif /* __THGAMESONGH__ */
