
/**************************************************************
 *	
 *	THLoseSound, 8 bit, 11025Hz,
 *	1 channel, 46368 bytes/channel
 *	Total Size: 1 * 46368 + 4 (header) = 46412 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Spring2019\CS2261\Final Project\Sound\Sound\EditedSongs\Sound Effects\THLoseSound.wav
 *	Time-stamp: Wed Apr 17 02:04:57 2019
 *	
 **************************************************************/

#ifndef __THLOSESOUNDH__
#define __THLOSESOUNDH__

#define THLOSESOUNDFREQ 11025
#define THLOSESOUNDLEN 46368

extern const unsigned char THLoseSound[46368];

#endif /* __THLOSESOUNDH__ */
