
/**************************************************************
 *	
 *	transitionSound, 8 bit, 11025Hz,
 *	1 channel, 7488 bytes/channel
 *	Total Size: 1 * 7488 + 4 (header) = 7532 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Spring2019\CS2261\Final Project\Sound\Sound\EditedSongs\Sound Effects\transitionSound.wav
 *	Time-stamp: Wed Apr 17 02:11:53 2019
 *	
 **************************************************************/

#ifndef __TRANSITIONSOUNDH__
#define __TRANSITIONSOUNDH__

#define TRANSITIONSOUNDFREQ 11025
#define TRANSITIONSOUNDLEN 7488

extern const unsigned char transitionSound[7488];

#endif /* __TRANSITIONSOUNDH__ */
