
/**************************************************************
 *	
 *	walkingSound, 8 bit, 11025Hz,
 *	1 channel, 14688 bytes/channel
 *	Total Size: 1 * 14688 + 4 (header) = 14732 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Spring2019\CS2261\Final Project\Sound\Sound\EditedSongs\Sound Effects\walkingSound.wav
 *	Time-stamp: Tue Apr 23 13:30:28 2019
 *	
 **************************************************************/

#ifndef __WALKINGSOUNDH__
#define __WALKINGSOUNDH__

#define WALKINGSOUNDFREQ 11025
#define WALKINGSOUNDLEN 14688

extern const unsigned char walkingSound[14688];

#endif /* __WALKINGSOUNDH__ */
